### ISSUE TITLE
Install Heap Analytics on all pages

### ISSUE THREAD

**Issue by seanconnollydev** [seanconnollydev/yahoo-fantasy-football-tools#52]
&lt;script type="text/javascript"&gt;
    var heap=heap||[];heap.load=function(a){window._heapid=a;var b=document.createElement("script");b.type="text/javascript",b.async=!0,b.src=("https:"===document.location.protocol?"https:":"http:")+"//d36lvucg9kzous.cloudfront.net";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c);var d=function(a){return function(){heap.push([a].concat(Array.prototype.slice.call(arguments,0)))}},e=["identify","track"];for(var f=0;f<e.length;f++)heap[e[f]]=d(e[f])};
    heap.load("YOUR_APP_ID");
  &lt;/script&gt;

**Comment by seanconnollydev** [comment]
Heap Analytics does not have a free trial, so I don't plan on testing this out.

**Comment by drob** [comment]
Hey @sconno05,

Just came across this. We now offer a 60 day free trial. Shoot me an email at dan@heapanalytics.com if you have any questions!

Best,
-Dan
